sudo: false
language: php
cache:
  directories:
        - $HOME/.composer/cache
php:
  - 7.2

install:
  - composer require "phpunit/phpunit=5.7.*"
  - composer install

before_script:
  - php -S localhost:8888 index.php &

script:
  - sh -c "cd tests/integration/ && ../../vendor/bin/behat ."
  - sh -c "cd tests/unit/ && ../../vendor/bin/phpunit ."
