sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0

install:
  - sh -c "composer install"

before_script:
  - php -S localhost:8888 index.php &

script:
  - sh -c "cd tests/integration/ && ../../vendor/bin/behat ."
  - sh -c "cd tests/unit/ && phpunit ."
